
import java.text.SimpleDateFormat;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class KayitEkrani extends javax.swing.JFrame {

    Baglanti islemler = new Baglanti();
    
    public KayitEkrani() {
        initComponents();
        
        mesaj_kullanici.setVisible(false);
        mesaj_mail.setVisible(false);
        mesaj_tur.setVisible(false);
        mesaj_sifre.setVisible(false);
        mesaj_tur.setVisible(false);
        mesaj_tarih.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        text_kullanici = new javax.swing.JTextField();
        button_kayit = new javax.swing.JButton();
        text_aksiyon = new javax.swing.JCheckBox();
        text_belgesel = new javax.swing.JCheckBox();
        text_bilimkurgu = new javax.swing.JCheckBox();
        text_cocuk = new javax.swing.JCheckBox();
        text_dramalar = new javax.swing.JCheckBox();
        text_gerilim = new javax.swing.JCheckBox();
        text_komedi = new javax.swing.JCheckBox();
        text_korku = new javax.swing.JCheckBox();
        text_romantizm = new javax.swing.JCheckBox();
        text_bilim = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mesaj_kullanici = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        text_mail = new javax.swing.JTextField();
        mesaj_mail = new javax.swing.JLabel();
        mesaj_tur = new javax.swing.JLabel();
        text_tarih = new com.toedter.calendar.JDateChooser();
        mesaj_tarih = new javax.swing.JLabel();
        text_sifre = new javax.swing.JPasswordField();
        mesaj_sifre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1005, 551));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        jLabel1.setText("Kullanici Adi");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 70, 120, 32);
        getContentPane().add(text_kullanici);
        text_kullanici.setBounds(410, 70, 120, 32);

        button_kayit.setText("Kayit Ol");
        button_kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_kayitActionPerformed(evt);
            }
        });
        getContentPane().add(button_kayit);
        button_kayit.setBounds(420, 430, 114, 42);

        text_aksiyon.setText("Aksiyon ve Macera");
        getContentPane().add(text_aksiyon);
        text_aksiyon.setBounds(400, 290, 200, 20);

        text_belgesel.setText("Belgesel");
        getContentPane().add(text_belgesel);
        text_belgesel.setBounds(610, 350, 100, 23);

        text_bilimkurgu.setText("Bilim Kurgu ve Fantastik Yapimlar");
        getContentPane().add(text_bilimkurgu);
        text_bilimkurgu.setBounds(400, 320, 200, 23);

        text_cocuk.setText("Cocuk ve Aile");
        getContentPane().add(text_cocuk);
        text_cocuk.setBounds(610, 320, 100, 23);

        text_dramalar.setText("Dramalar");
        getContentPane().add(text_dramalar);
        text_dramalar.setBounds(610, 290, 81, 23);

        text_gerilim.setText("Gerilim");
        getContentPane().add(text_gerilim);
        text_gerilim.setBounds(820, 290, 81, 23);

        text_komedi.setText("Komedi");
        getContentPane().add(text_komedi);
        text_komedi.setBounds(720, 290, 81, 23);

        text_korku.setText("Korku");
        getContentPane().add(text_korku);
        text_korku.setBounds(720, 320, 81, 23);

        text_romantizm.setText("Romantizm");
        getContentPane().add(text_romantizm);
        text_romantizm.setBounds(400, 350, 170, 23);

        text_bilim.setText("Bilim ve Doga");
        getContentPane().add(text_bilim);
        text_bilim.setBounds(720, 350, 100, 23);

        jLabel4.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        jLabel4.setText("Sifre");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 110, 120, 30);

        jLabel2.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        jLabel2.setText("Dogum Tarihi");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 150, 130, 50);

        jLabel8.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        jLabel8.setText("Uc tane tur seciniz");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 290, 150, 20);

        mesaj_kullanici.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        mesaj_kullanici.setText("Baska bir kullanici adi giriniz");
        getContentPane().add(mesaj_kullanici);
        mesaj_kullanici.setBounds(560, 70, 220, 30);

        jLabel12.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        jLabel12.setText("Mail");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(280, 230, 90, 16);
        getContentPane().add(text_mail);
        text_mail.setBounds(410, 230, 150, 30);

        mesaj_mail.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        mesaj_mail.setText("Baska bir mail giriniz");
        getContentPane().add(mesaj_mail);
        mesaj_mail.setBounds(590, 230, 150, 20);

        mesaj_tur.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        mesaj_tur.setText("Lutfen uc tane tur seciniz");
        getContentPane().add(mesaj_tur);
        mesaj_tur.setBounds(360, 380, 390, 30);
        getContentPane().add(text_tarih);
        text_tarih.setBounds(410, 170, 120, 30);

        mesaj_tarih.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        mesaj_tarih.setText("Lutfen dogum tarihinizi seciniz");
        getContentPane().add(mesaj_tarih);
        mesaj_tarih.setBounds(770, 140, 230, 30);
        getContentPane().add(text_sifre);
        text_sifre.setBounds(410, 120, 120, 30);

        mesaj_sifre.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        mesaj_sifre.setText("Sifre giriniz");
        getContentPane().add(mesaj_sifre);
        mesaj_sifre.setBounds(560, 120, 130, 30);

        jLabel3.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        jLabel3.setText("Takvim butonuna basip sonra doğum tarihinizi seciniz");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 170, 410, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim25.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1000, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_kayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_kayitActionPerformed
        
        String kulanici_adi = text_kullanici.getText();
        String sifre = String.valueOf(text_sifre.getPassword());
        String mail = text_mail.getText();
        boolean[] arr = new boolean[10];
        int i,j;
        String dogum_tarihi=" ";
        j=0;
        for(i=0;i<10;i++){
            arr[i]=false;
        }
        arr[0] = text_aksiyon.isSelected();
        arr[1] = text_bilimkurgu.isSelected();
        arr[2] = text_romantizm.isSelected();
        arr[3] = text_dramalar.isSelected();
        arr[4] = text_cocuk.isSelected();
        arr[5] = text_belgesel.isSelected();
        arr[6] = text_komedi.isSelected();
        arr[7] = text_korku.isSelected();
        arr[8] = text_bilim.isSelected();
        arr[9] = text_gerilim.isSelected();
        for(i=0;i<10;i++){
            if(arr[i]==true){
                j++;
            }
        }
        if(kulanici_adi.equals("")==true){
            mesaj_kullanici.setVisible(true);
        };
        if(sifre.equals("")==true){
            mesaj_sifre.setVisible(true);
        };
        if(j!=3){
            mesaj_tur.setVisible(true);
        }
        boolean kullanici_bool = islemler.kullanici_kayit(kulanici_adi);
        if(kullanici_bool == true){
            mesaj_kullanici.setVisible(true);
        }
        boolean mail_bool = islemler.mail_adresi_kayit(mail);
        if(mail_bool == true || mail.equals("")==true){
            mesaj_mail.setVisible(true);
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        boolean tarih_bool;
        if(text_tarih.getDate()==null){
            tarih_bool = true;
            mesaj_tarih.setVisible(true);
        }
        else{
            dogum_tarihi = sdf.format(text_tarih.getDate());
            tarih_bool = false;
        }
        if(kullanici_bool == false && mail_bool==false && tarih_bool==false && j==3
         && kulanici_adi.equals("")==false && sifre.equals("")==false && mail.equals("")==false){
            islemler.yenikayit(kulanici_adi, sifre, mail, dogum_tarihi);
            KayitSonrasiEkrani kayit_sonrasi_ekrani = new KayitSonrasiEkrani(arr);
            kayit_sonrasi_ekrani.setVisible(true);
            setVisible(false);
        } 
      
    }//GEN-LAST:event_button_kayitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KayitEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_kayit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel mesaj_kullanici;
    private javax.swing.JLabel mesaj_mail;
    private javax.swing.JLabel mesaj_sifre;
    private javax.swing.JLabel mesaj_tarih;
    private javax.swing.JLabel mesaj_tur;
    private javax.swing.JCheckBox text_aksiyon;
    private javax.swing.JCheckBox text_belgesel;
    private javax.swing.JCheckBox text_bilim;
    private javax.swing.JCheckBox text_bilimkurgu;
    private javax.swing.JCheckBox text_cocuk;
    private javax.swing.JCheckBox text_dramalar;
    private javax.swing.JCheckBox text_gerilim;
    private javax.swing.JCheckBox text_komedi;
    private javax.swing.JCheckBox text_korku;
    private javax.swing.JTextField text_kullanici;
    private javax.swing.JTextField text_mail;
    private javax.swing.JCheckBox text_romantizm;
    private javax.swing.JPasswordField text_sifre;
    private com.toedter.calendar.JDateChooser text_tarih;
    // End of variables declaration//GEN-END:variables
}
