
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Yonetim extends javax.swing.JFrame {

    DefaultTableModel model;
    Baglanti islemler = new Baglanti();
    ArrayList<KullaniciYonetim> kullanici  = new ArrayList<KullaniciYonetim>();
    ArrayList<YeniClass> yeniclass = new ArrayList<YeniClass>();
    int kullanici_id;
    Date currentDate = new Date();
    Date currentDate2 = new Date();
    int baslangic=0;
    int son=0;
    int cevap = 0;
    int bool1=2;
    int bool2=0;
    int sure=0;
    int izleden = 0;
    /**
     * Creates new form Yonetim
     */
    public Yonetim() {
        initComponents();
        
    }
    public Yonetim(int kullanicci) {
        initComponents();
        this.kullanici_id = kullanicci;
        model=(DefaultTableModel) text_tablo.getModel();
        label_1.setVisible(false);
        text_izle.setVisible(false);
        text_bitir.setVisible(false);
        label_puan.setVisible(false);
        text_puan.setVisible(false);
        label_izle.setVisible(false);
        label_2.setVisible(false);
        buton_bitir.setVisible(false);
        text_label.setVisible(false);
        text_zaman.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    private static int toMins(String s) {
        
    String[] hourMin = s.split(":");
    int hour = Integer.parseInt(hourMin[0]);
    if(hour>12){
        hour = hour - 12;
    }
    int mins = Integer.parseInt(hourMin[1]);
    int seconds = Integer.parseInt(hourMin[2]);
    return hour * 1200 + mins*60 + seconds;
    
}
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        text_tablo = new javax.swing.JTable();
        arama_cubugu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        label_1 = new javax.swing.JLabel();
        text_izle = new javax.swing.JButton();
        text_bitir = new javax.swing.JButton();
        label_2 = new javax.swing.JLabel();
        text_puan = new javax.swing.JComboBox<>();
        label_puan = new javax.swing.JLabel();
        label_izle = new javax.swing.JLabel();
        buton_bitir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        text_label = new javax.swing.JLabel();
        text_zaman = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1641, 741));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jScrollPane1.setEnabled(false);

        text_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Program", "Program Turu", "Program Tipi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        text_tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_tabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(text_tablo);
        if (text_tablo.getColumnModel().getColumnCount() > 0) {
            text_tablo.getColumnModel().getColumn(0).setResizable(false);
            text_tablo.getColumnModel().getColumn(1).setResizable(false);
            text_tablo.getColumnModel().getColumn(2).setResizable(false);
            text_tablo.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 330, 1100, 320);
        getContentPane().add(arama_cubugu);
        arama_cubugu.setBounds(380, 10, 689, 55);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        jButton1.setText("Ara");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(114, 11, 235, 55);

        label_1.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        label_1.setText("Film");
        getContentPane().add(label_1);
        label_1.setBounds(420, 90, 400, 60);

        text_izle.setBackground(new java.awt.Color(255, 0, 0));
        text_izle.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 12)); // NOI18N
        text_izle.setText("Izle");
        text_izle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_izleActionPerformed(evt);
            }
        });
        getContentPane().add(text_izle);
        text_izle.setBounds(410, 160, 188, 50);

        text_bitir.setBackground(new java.awt.Color(255, 0, 0));
        text_bitir.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        text_bitir.setText("Durdur");
        text_bitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_bitirActionPerformed(evt);
            }
        });
        getContentPane().add(text_bitir);
        text_bitir.setBounds(610, 160, 210, 51);

        label_2.setText("id");
        getContentPane().add(label_2);
        label_2.setBounds(50, 70, 50, 40);

        text_puan.setBackground(new java.awt.Color(255, 0, 0));
        text_puan.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        text_puan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(text_puan);
        text_puan.setBounds(610, 230, 210, 30);

        label_puan.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        label_puan.setText("Puan Veriniz");
        getContentPane().add(label_puan);
        label_puan.setBounds(410, 230, 190, 30);

        label_izle.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        label_izle.setText("Film Izleniyor");
        getContentPane().add(label_izle);
        label_izle.setBounds(840, 90, 230, 50);

        buton_bitir.setBackground(new java.awt.Color(255, 0, 0));
        buton_bitir.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        buton_bitir.setText("Bitir");
        buton_bitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_bitirActionPerformed(evt);
            }
        });
        getContentPane().add(buton_bitir);
        buton_bitir.setBounds(830, 160, 210, 50);

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        jLabel1.setText("Film veya Tur Arayiniz");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 110, 250, 50);

        text_label.setBackground(new java.awt.Color(255, 255, 255));
        text_label.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        text_label.setText("Izlenen Dakika");
        getContentPane().add(text_label);
        text_label.setBounds(410, 270, 130, 40);

        text_zaman.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        getContentPane().add(text_zaman);
        text_zaman.setBounds(610, 270, 130, 30);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1140, 10, 110, 50);

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Verdana Pro Black", 0, 12)); // NOI18N
        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1140, 80, 110, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String ara = arama_cubugu.getText();
        model.setRowCount(0);
        int i;
        int j;
        boolean bool = islemler.empty(kullanici_id);
        if(bool == true){
            kullanici=islemler.kullanici_tablo(ara);
            System.out.println(kullanici.size());
            for(i=0;i<kullanici.size();i++){
            Object[] eklenecek = {kullanici.get(i).getProgram_id(),kullanici.get(i).getProgram_adi(),kullanici.get(i).getProgram_turu(),kullanici.get(i).getProgram_tipi() };
            model.addRow(eklenecek);
        }
        }
        else{
            kullanici=islemler.kullanici_tablo(ara);
            yeniclass=islemler.fonk(kullanici_id);
            System.out.println(yeniclass.size());
            for(i=0;i<kullanici.size();i++){
            Object[] eklenecek = {kullanici.get(i).getProgram_id(),kullanici.get(i).getProgram_adi(),kullanici.get(i).getProgram_turu(),kullanici.get(i).getProgram_tipi() };
            model.addRow(eklenecek);
        }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void text_tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_tabloMouseClicked
        
        int selectedrow = text_tablo.getSelectedRow();
        label_1.setText(model.getValueAt(selectedrow, 1).toString());
        label_2.setText(model.getValueAt(selectedrow, 0).toString());
        label_1.setVisible(true);
        text_izle.setVisible(true);
        
    }//GEN-LAST:event_text_tabloMouseClicked

    private void text_izleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_izleActionPerformed
        
        bool1=1;
        izleden=0;
        text_izle.setVisible(false);
        label_izle.setVisible(true);
        text_bitir.setVisible(true);
        buton_bitir.setVisible(false);
        jButton1.setVisible(false);
        label_izle.setText("Film Izleniyor");
        jButton1.setVisible(false);
        SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");  
        Date date = new Date();  
        System.out.println(formatter.format(date));
        baslangic=toMins(formatter.format(date));
        while(model.getRowCount() > 0)
        {
           model.removeRow(0);
        }
        String temp1 = label_2.getText().toString();
        int temp5=Integer.parseInt(temp1);
        if(bool2==0){
        sure=islemler.fonk_sure(temp5, kullanici_id);
        cevap=sure;
        }
        
    }//GEN-LAST:event_text_izleActionPerformed

    private void text_bitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_bitirActionPerformed

        bool1=1;
        bool2=1;
        text_izle.setVisible(true);
        label_puan.setVisible(true);
        text_puan.setVisible(true);
        text_label.setVisible(true);
        text_zaman.setVisible(true);
        label_izle.setText("Film Durduruldu");
        buton_bitir.setVisible(true);
        text_bitir.setVisible(false);
        text_izle.setText("Devam Et");
        SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");  
        Date date = new Date();  
        System.out.println(formatter.format(date));
        son = toMins(formatter.format(date));
        cevap = son - baslangic + cevap ;
        text_zaman.setText(Integer.toString(cevap));
        izleden=1;
        
    }//GEN-LAST:event_text_bitirActionPerformed

    private void buton_bitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_bitirActionPerformed

        bool1=2;
        bool2=0;
        sure=0;
        label_1.setVisible(false);
        text_izle.setVisible(false);
        text_bitir.setVisible(false);
        label_puan.setVisible(false);
        text_puan.setVisible(false);
        label_izle.setVisible(false);
        label_2.setVisible(false);
        buton_bitir.setVisible(false);
        jButton1.setVisible(true);
        text_izle.setText("Izle");
        text_label.setVisible(false);
        text_zaman.setVisible(false);
        int i,j;
        if(label_1.getText().equals("Film")!=true){
            String ara = label_1.getText();
            int pg_id = Integer.parseInt(label_2.getText());
            int program_zamani=0;
            int bolum=1;
            int puan=5;
            puan = text_puan.getSelectedIndex();
            puan = puan + 1;
            if(islemler.empty_button(kullanici_id, pg_id)==true){
                for(i=0;i<kullanici.size();i++){
                    for(j=0;j<yeniclass.size();j++){
                    if(kullanici_id == yeniclass.get(j).getKullanici_id() && 
                          kullanici.get(i).getProgram_id()==yeniclass.get(j).getProgram_id() ){
                    program_zamani=cevap;
                    bolum=yeniclass.get(j).getBolum();
                    }
                    } 
            }
                islemler.kullanici_yenileme(kullanici_id, pg_id, program_zamani, bolum , puan);
                while(model.getRowCount() > 0)
                {
                    model.removeRow(0);
                }
            }
            else{
             for(i=0;i<kullanici.size();i++){
                if(kullanici.get(i).getProgram_adi().equals(ara)){
                    program_zamani=cevap;
                    bolum=kullanici.get(i).getIzlenen_bolum();
                }
                }
                islemler.kullanici_kayit(kullanici_id, pg_id, program_zamani, bolum , puan);
                while(model.getRowCount() > 0)
                {
                    model.removeRow(0);
                }
            }
        }
        else{
        }
        cevap=0;
        
    }//GEN-LAST:event_buton_bitirActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        int i,j;
        if(izleden==0){
        SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");
        Date date = new Date();  
        son = toMins(formatter.format(date));
        }
        if(bool1==1){
            String ara = label_1.getText();
            int pg_id = Integer.parseInt(label_2.getText());
            int program_zamani=0;
            int bolum=1;
            int puan=5;
            puan = text_puan.getSelectedIndex();
            puan = puan + 1;
            if(islemler.empty_button(kullanici_id, pg_id)==true){
                for(i=0;i<kullanici.size();i++){
                    for(j=0;j<yeniclass.size();j++){
                    if(kullanici_id == yeniclass.get(j).getKullanici_id() && 
                          kullanici.get(i).getProgram_id()==yeniclass.get(j).getProgram_id() ){
                    program_zamani=son - baslangic + cevap;
                    bolum=yeniclass.get(j).getBolum();
                    }
                    } 
            }
                islemler.kullanici_yenileme(kullanici_id, pg_id, program_zamani, bolum , puan);
                while(model.getRowCount() > 0)
                {
                    model.removeRow(0);
                }
            }
            else{
             for(i=0;i<kullanici.size();i++){
                if(kullanici.get(i).getProgram_adi().equals(ara)){
                    program_zamani=son - baslangic + cevap;
                    bolum=kullanici.get(i).getIzlenen_bolum();
                }
                }
                islemler.kullanici_kayit(kullanici_id, pg_id, program_zamani, bolum , puan);
                while(model.getRowCount() > 0)
                {
                    model.removeRow(0);
                }
            }
        }
        else{
        }
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yonetim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yonetim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yonetim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yonetim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Yonetim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JButton buton_bitir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_1;
    private javax.swing.JLabel label_2;
    private javax.swing.JLabel label_izle;
    private javax.swing.JLabel label_puan;
    private javax.swing.JButton text_bitir;
    private javax.swing.JButton text_izle;
    private javax.swing.JLabel text_label;
    private javax.swing.JComboBox<String> text_puan;
    private javax.swing.JTable text_tablo;
    private javax.swing.JLabel text_zaman;
    // End of variables declaration//GEN-END:variables
}
